In [23]:
# Import required libraries
import numpy as np
import pandas as pd
import hvplot.pandas
from pathlib import Path
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [24]:
data = pd.read_csv('training_data.csv')
data.head()

name team position  games  receptions  targets  receiving_yards  \
0  A.J. Brown  TEN       WR     16          52       84           1051.0   
1  A.J. Brown  TEN       WR     14          70      106           1075.0   
2  A.J. Brown  TEN       WR     13          63      105            869.0   
3  A.J. Brown  PHI       WR     17          88      145           1496.0   
4  A.J. Brown  PHI       WR     17         106      158           1456.0   

   rec_ypg  receiving_tds    ypr  ...  sacks  sack_fumbles  offense_snaps  \
0    65.69              8  20.21  ...    0.0             0          678.0   
1    76.79             11  15.36  ...    0.0             0          760.0   
2    66.85              5  13.79  ...    0.0             0          604.0   
3    88.00             11  17.00  ...    0.0             0         1004.0   
4    85.65              7  13.74  ...    0.0             0         1019.0   

   teams_offense_snaps  round  overall             stadium_name  \
0                997.0    2.0     51.0           Nissan Stadium   
1                945.0    2.0     51.0           Nissan Stadium   
2                876.0    2.0     51.0           Nissan Stadium   
3               1189.0    2.0     51.0  Lincoln Financial Field   
4               1154.0    2.0     51.0  Lincoln Financial Field   

   stadium_weather_type  stadium_surface  fantasy_points_ppr  
0              moderate            Grass               217.1  
1              moderate            Grass               247.5  
2              moderate            Grass               180.9  
3                  cold            Grass               299.6  
4                  cold            Grass               289.6  

[5 rows x 40 columns]

In [25]:
data = data.drop(columns = ['name', 'team', 'stadium_name'])
data

position  games  receptions  targets  receiving_yards  rec_ypg  \
0          WR     16          52       84           1051.0    65.69   
1          WR     14          70      106           1075.0    76.79   
2          WR     13          63      105            869.0    66.85   
3          WR     17          88      145           1496.0    88.00   
4          WR     17         106      158           1456.0    85.65   
...       ...    ...         ...      ...              ...      ...   
2101       WR     16          56      102            652.0    40.75   
2102       WR     11          14       20            154.0    14.00   
2103       WR     15          47       70            546.0    36.40   
2104       WR     16          82      121            823.0    51.44   
2105       WR      9          34       64            321.0    35.67   

      receiving_tds    ypr  receiving_fumbles  receiving_2pt_conversions  ...  \
0                 8  20.21                1.0                          0  ...   
1                11  15.36                2.0                          0  ...   
2                 5  13.79                0.0                          0  ...   
3                11  17.00                2.0                          0  ...   
4                 7  13.74                2.0                          0  ...   
...             ...    ...                ...                        ...  ...   
2101              7  11.64                1.0                          1  ...   
2102              1  11.00                0.0                          0  ...   
2103              1  11.62                1.0                          0  ...   
2104              5  10.04                0.0                          1  ...   
2105              2   9.44                0.0                          0  ...   

      interceptions  sacks  sack_fumbles  offense_snaps  teams_offense_snaps  \
0               0.0    0.0             0          678.0                997.0   
1               0.0    0.0             0          760.0                945.0   
2               0.0    0.0             0          604.0                876.0   
3               0.0    0.0             0         1004.0               1189.0   
4               0.0    0.0             0         1019.0               1154.0   
...             ...    ...           ...            ...                  ...   
2101            0.0    0.0             0          941.0               1063.0   
2102            0.0    0.0             0          248.0                771.0   
2103            0.0    0.0             0          614.0               1026.0   
2104            0.0    0.0             0          930.0               1082.0   
2105            0.0    0.0             0          475.0                655.0   

      round  overall  stadium_weather_type  stadium_surface  \
0       2.0     51.0              moderate            Grass   
1       2.0     51.0              moderate            Grass   
2       2.0     51.0              moderate            Grass   
3       2.0     51.0                  cold            Grass   
4       2.0     51.0                  cold            Grass   
...     ...      ...                   ...              ...   
2101    2.0     37.0                  cold        FieldTurf   
2102    2.0     37.0                indoor            Grass   
2103    2.0     37.0                indoor            Grass   
2104    2.0     37.0                  warm            Grass   
2105    2.0     37.0                  warm            Grass   

      fantasy_points_ppr  
0                 217.10  
1                 247.50  
2                 180.90  
3                 299.60  
4                 289.60  
...                  ...  
2101              165.20  
2102               36.56  
2103              105.90  
2104              198.10  
2105               78.10  

[2106 rows x 37 columns]

In [26]:
# Encoding categorical columns for model
encoded_data = pd.get_dummies(data)
encoded_data

games  receptions  targets  receiving_yards  rec_ypg  receiving_tds  \
0        16          52       84           1051.0    65.69              8   
1        14          70      106           1075.0    76.79             11   
2        13          63      105            869.0    66.85              5   
3        17          88      145           1496.0    88.00             11   
4        17         106      158           1456.0    85.65              7   
...     ...         ...      ...              ...      ...            ...   
2101     16          56      102            652.0    40.75              7   
2102     11          14       20            154.0    14.00              1   
2103     15          47       70            546.0    36.40              1   
2104     16          82      121            823.0    51.44              5   
2105      9          34       64            321.0    35.67              2   

        ypr  receiving_fumbles  receiving_2pt_conversions  target_share  ...  \
0     20.21                1.0                          0          0.20  ...   
1     15.36                2.0                          0          0.27  ...   
2     13.79                0.0                          0          0.28  ...   
3     17.00                2.0                          0          0.29  ...   
4     13.74                2.0                          0          0.30  ...   
...     ...                ...                        ...           ...  ...   
2101  11.64                1.0                          1          0.21  ...   
2102  11.00                0.0                          0          0.05  ...   
2103  11.62                1.0                          0          0.14  ...   
2104  10.04                0.0                          1          0.22  ...   
2105   9.44                0.0                          0          0.18  ...   

      position_QB  position_RB  position_TE  position_WR  \
0           False        False        False         True   
1           False        False        False         True   
2           False        False        False         True   
3           False        False        False         True   
4           False        False        False         True   
...           ...          ...          ...          ...   
2101        False        False        False         True   
2102        False        False        False         True   
2103        False        False        False         True   
2104        False        False        False         True   
2105        False        False        False         True   

      stadium_weather_type_cold  stadium_weather_type_indoor  \
0                         False                        False   
1                         False                        False   
2                         False                        False   
3                          True                        False   
4                          True                        False   
...                         ...                          ...   
2101                       True                        False   
2102                      False                         True   
2103                      False                         True   
2104                      False                        False   
2105                      False                        False   

      stadium_weather_type_moderate  stadium_weather_type_warm  \
0                              True                      False   
1                              True                      False   
2                              True                      False   
3                             False                      False   
4                             False                      False   
...                             ...                        ...   
2101                          False                      False   
2102                          False                      False   
2103                          False 

In [27]:
# Defining y (target variable)
y = encoded_data['fantasy_points_ppr']

# Defining X (features)
X = encoded_data.drop(columns = 'fantasy_points_ppr')

X.shape

(2106, 43)

In [28]:
# Spliting model into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=42)

In [29]:
lr_model = LinearRegression()

In [30]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [31]:
intercept = lr_model.intercept_
intercept

0.12448781746863347

In [32]:
m = lr_model.coef_
m

array([ 1.75444234e-02,  1.01753689e+00, -1.45173159e-02,  1.00590722e-01,
       -1.90191074e-03,  6.01454392e+00, -3.11527065e-03, -1.07569148e+00,
        1.93219596e+00, -3.91985303e-01, -1.81358177e+00, -2.12849054e-02,
        1.03933946e-01,  1.12333336e-03,  6.00318824e+00, -1.81163127e-01,
       -6.76741278e-01,  2.01258324e+00, -3.32490437e-02,  1.06296629e-02,
        7.81682088e-02,  4.13728124e-02, -5.15534819e-04,  4.01641722e+00,
        1.81421035e+00,  6.85271962e-02, -1.96771403e+00,  2.77440984e-02,
       -1.06092070e+00, -6.61760110e-04,  3.67720436e-04,  2.34551708e-02,
       -1.60844500e-03, -1.86875971e-01, -1.89873657e-01, -1.10310057e-01,
        4.87059685e-01,  1.21896194e-02,  6.81013170e-02,  9.39123105e-02,
       -1.74203247e-01, -3.29541480e-02,  3.29541480e-02])

In [33]:
predictions = lr_model.predict(X_train)

In [34]:
len(predictions)

1579

In [35]:
r2_score(y_train, predictions)

0.9997549643470564

In [36]:
mse = mean_squared_error(y_train, predictions)
mse

2.3476187172427223

In [37]:
prediction_data = pd.read_csv('predicting_data.csv')
prediction_data.head()

name team position      games  receptions     targets  \
0     A.J. Brown  PHI       WR  15.400000   75.800000  119.600000   
1     A.T. Perry   NO       WR   8.000000   12.000000   18.000000   
2    AJ McCarron  CIN       QB   2.000000    0.000000    0.000000   
3    Aaron Jones   GB       RB  13.571429   38.857143   52.000000   
4  Aaron Rodgers  NYJ       QB  13.272727    0.181818    0.181818   

   receiving_yards    rec_ypg  receiving_tds        ypr  ...  interceptions  \
0      1189.400000  76.596000       8.400000  16.020000  ...       0.000000   
1       246.000000  30.750000       4.000000  20.500000  ...       0.000000   
2         0.000000   0.000000       0.000000   0.000000  ...       0.250000   
3       296.571429  20.691429       2.571429   7.080000  ...       0.000000   
4        -0.909091  -0.057273       0.000000  -0.909091  ...       5.363636   

       sacks  sack_fumbles  offense_snaps  teams_offense_snaps  round  \
0   0.000000      0.000000     813.000000          1032.200000    2.0   
1   0.000000      0.000000     319.000000           519.000000    6.0   
2   2.000000      0.000000       0.000000             0.000000    0.0   
3   0.000000      0.000000     482.285714           890.285714    5.0   
4  29.090909      3.363636     847.636364           891.181818    1.0   

   overall             stadium_name  stadium_weather_type  stadium_surface  
0     51.0  Lincoln Financial Field                  cold            Grass  
1    195.0  Mercedes-Benz Superdome                indoor        FieldTurf  
2      0.0       Paul Brown Stadium                  cold        FieldTurf  
3    182.0            Lambeau Field                  cold            Grass  
4     24.0          MetLife Stadium                  cold        FieldTurf  

[5 rows x 39 columns]

In [38]:
prediction_data_cleaned = prediction_data.drop(columns = ['name', 'team', 'stadium_name'])
prediction_data_cleaned.head()

position      games  receptions     targets  receiving_yards    rec_ypg  \
0       WR  15.400000   75.800000  119.600000      1189.400000  76.596000   
1       WR   8.000000   12.000000   18.000000       246.000000  30.750000   
2       QB   2.000000    0.000000    0.000000         0.000000   0.000000   
3       RB  13.571429   38.857143   52.000000       296.571429  20.691429   
4       QB  13.272727    0.181818    0.181818        -0.909091  -0.057273   

   receiving_tds        ypr  receiving_fumbles  receiving_2pt_conversions  \
0       8.400000  16.020000           1.400000                   0.000000   
1       4.000000  20.500000           0.000000                   0.000000   
2       0.000000   0.000000           0.000000                   0.000000   
3       2.571429   7.080000           0.857143                   0.142857   
4       0.000000  -0.909091           0.000000                   0.000000   

   ...  td_percentage  interceptions      sacks  sack_fumbles  offense_snaps  \
0  ...       0.116000       0.000000   0.000000      0.000000     813.000000   
1  ...       0.330000       0.000000   0.000000      0.000000     319.000000   
2  ...       0.005000       0.250000   2.000000      0.000000       0.000000   
3  ...       0.042857       0.000000   0.000000      0.000000     482.285714   
4  ...       0.052727       5.363636  29.090909      3.363636     847.636364   

   teams_offense_snaps  round  overall  stadium_weather_type  stadium_surface  
0          1032.200000    2.0     51.0                  cold            Grass  
1           519.000000    6.0    195.0                indoor        FieldTurf  
2             0.000000    0.0      0.0                  cold        FieldTurf  
3           890.285714    5.0    182.0                  cold            Grass  
4           891.181818    1.0     24.0                  cold        FieldTurf  

[5 rows x 36 columns]

In [39]:
# Encoding categorical columns for model
encoded_prediction_data = pd.get_dummies(prediction_data_cleaned)
encoded_prediction_data

games  receptions     targets  receiving_yards    rec_ypg  \
0    15.400000   75.800000  119.600000      1189.400000  76.596000   
1     8.000000   12.000000   18.000000       246.000000  30.750000   
2     2.000000    0.000000    0.000000         0.000000   0.000000   
3    13.571429   38.857143   52.000000       296.571429  20.691429   
4    13.272727    0.181818    0.181818        -0.909091  -0.057273   
..         ...         ...         ...              ...        ...   
519  11.333333    0.333333    0.666667         0.666667   0.073333   
520  12.000000   17.000000   23.000000       124.000000   9.417500   
521  12.000000    7.500000    9.500000        49.000000   3.770000   
522  16.000000   77.000000  108.000000       858.000000  53.620000   
523  13.500000   43.333333   75.166667       468.666667  33.471667   

     receiving_tds        ypr  receiving_fumbles  receiving_2pt_conversions  \
0         8.400000  16.020000           1.400000                   0.000000   
1         4.000000  20.500000           0.000000                   0.000000   
2         0.000000   0.000000           0.000000                   0.000000   
3         2.571429   7.080000           0.857143                   0.142857   
4         0.000000  -0.909091           0.000000                   0.000000   
..             ...        ...                ...                        ...   
519       0.333333   0.666667           0.000000                   0.000000   
520       1.000000   6.367500           0.500000                   0.250000   
521       0.000000   3.265000           0.000000                   0.000000   
522       5.000000  11.140000           0.000000                   1.000000   
523       3.000000  10.906667           0.333333                   0.333333   

     target_share  ...  position_QB  position_RB  position_TE  position_WR  \
0        0.268000  ...        False        False        False         True   
1        0.070000  ...        False        False        False         True   
2        0.000000  ...         True        False        False        False   
3        0.115714  ...        False         True        False        False   
4        0.000000  ...         True        False        False        False   
..            ...  ...          ...          ...          ...          ...   
519      0.000000  ...         True        False        False        False   
520      0.050000  ...        False         True        False        False   
521      0.020000  ...        False         True        False        False   
522      0.240000  ...        False        False        False         True   
523      0.163333  ...        False        False        False         True   

     stadium_weather_type_cold  stadium_weather_type_indoor  \
0                         True                        False   
1                        False                         True   
2                         True                        False   
3                         True                        False   
4                         True                        False   
..                         ...                          ...   
519                       True                        False   
520                      False                         True   
521                      False                         True   
522                      False                        False   
523                      False                        False   

     stadium_weather_type_moderate  stadium_weather_type_warm  \
0                            False                      False   
1                            False                      False   
2                            False                      False   
3                            False                      False   
4                            False                      False   
..                             ...                        ...   
519                          False                      False   
520  

In [40]:
list_of_lists = encoded_prediction_data.values.tolist()  # Get a list of rows
test = list_of_lists[5]

real_predictions = lr_model.predict([test])
real_predictions

C:\Users\nmrod\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([178.86200935])

In [41]:
names_list = prediction_data['name'].tolist()

In [44]:
# Assuming encoded_prediction_data has data
list_of_lists = encoded_prediction_data.values.tolist()  # Get a list of rows

# Initialize an empty list to store all predictions
all_predictions = []

# Loop through each index from 0 to 524 (inclusive)
for index in range(524):
  # Get the data for the current index
  data_for_prediction = list_of_lists[index]

  # Make prediction using your model
  prediction = lr_model.predict([data_for_prediction])

  # Append the prediction to the all_predictions list
  all_predictions.append(prediction)  # Assuming single prediction per row

# Print or use the all_predictions list for further analysis
all_predictions

C:\Users\nmrod\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\nmrod\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\nmrod\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\nmrod\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\nmrod\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\nmrod\anaconda3\envs\dev\lib\site-pa

[array([246.42377132]),
 array([60.92915922]),
 array([5.32504847]),
 array([205.77054613]),
 array([262.34677345]),
 array([178.86200935]),
 array([51.87635856]),
 array([126.22002815]),
 array([32.83477321]),
 array([103.3697852]),
 array([9.31976538]),
 array([38.63831654]),
 array([101.33760648]),
 array([96.95718121]),
 array([152.75420344]),
 array([282.24939002]),
 array([219.91975345]),
 array([14.64439114]),
 array([57.8164022]),
 array([276.07841287]),
 array([51.15244481]),
 array([35.72714005]),
 array([185.31342958]),
 array([8.40374194]),
 array([72.23489777]),
 array([1.67001887]),
 array([182.337128]),
 array([237.29440913]),
 array([111.3743774]),
 array([5.40898251]),
 array([55.88402596]),
 array([203.53244527]),
 array([12.29518313]),
 array([43.70415143]),
 array([249.12400268]),
 array([34.15547941]),
 array([16.23192941]),
 array([45.83952063]),
 array([71.28571567]),
 array([200.21496707]),
 array([209.02835443]),
 array([42.63174523]),
 array([45.13742217]),
 a

In [45]:
fantasy_2024_predictions = pd.DataFrame(list(zip(names_list, all_predictions)), columns = ['name', '2024_Fantasy_Prediction'])
fantasy_2024_predictions = fantasy_2024_predictions.merge(prediction_data, how='left', on='name')
fantasy_2024_predictions = fantasy_2024_predictions[['name', 'team', 'position', '2024_Fantasy_Prediction']]
fantasy_2024_predictions

name team position 2024_Fantasy_Prediction
0       A.J. Brown  PHI       WR    [246.42377132126487]
1       A.T. Perry   NO       WR     [60.92915921981991]
2      AJ McCarron  CIN       QB     [5.325048472053764]
3      Aaron Jones   GB       RB    [205.77054612523557]
4    Aaron Rodgers  NYJ       QB     [262.3467734454945]
..             ...  ...      ...                     ...
519    Zach Wilson  NYJ       QB    [125.43427621849672]
520      Zack Moss  IND       RB    [105.64752626535525]
521    Zamir White   LV       RB    [41.205432172046585]
522    Zay Flowers  BAL       WR    [206.80830284305034]
523      Zay Jones  JAX       WR     [109.0568667383408]

[524 rows x 4 columns]

In [46]:
mse = mean_squared_error(y_train, real_predictions)
mse



ValueError: Found input variables with inconsistent numbers of samples: [1579, 524]

In [92]:
r2_score(y_train, real_predictions)

ValueError: Found input variables with inconsistent numbers of samples: [1579, 524]